language: php

php:
  - 5.4

before_install:
    - sudo apt-get update > /dev/null

install:
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-sqlite
    - sudo sed -i -e "s,/var/www,$(pwd)/features/fixtures/project/web,g" /etc/apache2/sites-available/default
    - sudo sed -i -e "/DocumentRoot/i\ServerName fsi-admin-translatable-bundle.dev" /etc/apache2/sites-available/default
    - echo "127.0.0.1 fsi-admin-translatable-bundle.dev" | sudo tee -a /etc/hosts
    - sudo sed -i -e "s/export APACHE_RUN_USER=.*/export APACHE_RUN_USER=travis/ ; s/export APACHE_RUN_GROUP=.*/export APACHE_RUN_GROUP=travis/" /etc/apache2/envvars
    - sudo chown -R travis:travis /var/lock/apache2
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.35.0.jar

before_script:
    - sudo /etc/init.d/apache2 restart
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - java -jar selenium-server-standalone-2.35.0.jar > /dev/null &
    - sleep 5

script:
    - composer self-update
    - composer --prefer-source --dev install
    - ./bin/phpspec run -f pretty
    - ./bin/behat --no-snippets --no-paths --verbose --format=progress
